"""Safely SEPARATE secrets from .env.example.

Relocates any non-placeholder secret values from .env.example into a local .env (which is
gitignored), and resets those lines in .env.example to blank placeholders. Secret VALUES are
read into memory only to move them — they are NEVER printed, logged, or returned. Only variable
NAMES are reported. Idempotent: if there is nothing to migrate it is a no-op.

Run once: python scripts/migrate_secrets_to_env.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from check_secret_hygiene import SECRET_VARS, classify  # noqa: E402

EXAMPLE = ROOT / ".env.example"
ENV = ROOT / ".env"


def main() -> int:
    if not EXAMPLE.exists():
        print(".env.example not found; nothing to do.")
        return 0
    src_lines = EXAMPLE.read_text().splitlines(keepends=False)

    # Build the new .env (full mirror of the template, secrets intact) and the cleaned template.
    env_lines = ["# Local secrets file. GITIGNORED. Do not commit. Generated by migrate_secrets_to_env.py.",
                 "# Real secret values live here; .env.example holds only placeholders."]
    cleaned_example: list[str] = []
    migrated: list[str] = []

    for line in src_lines:
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key, val = stripped.split("=", 1)
            key = key.strip()
            if key in SECRET_VARS and classify(val) == "SUSPECTED_SECRET":
                # move the value to .env (never printed); blank it in the template
                env_lines.append(f"{key}={val.strip()}")
                cleaned_example.append(f"{key}=")
                migrated.append(key)
                continue
        # non-secret config / comments / placeholders: keep in BOTH files
        cleaned_example.append(line)
        if stripped and not stripped.startswith("#") and "=" in stripped:
            env_lines.append(line)  # mirror config into .env so it is self-sufficient

    if not migrated:
        print("No non-placeholder secrets found in .env.example. Nothing migrated (already clean).")
        return 0

    # Never clobber an existing .env; require manual review in that case (no values printed).
    if ENV.exists():
        print(f".env already exists; not overwriting. {len(migrated)} secret var(s) still in "
              ".env.example need manual relocation (names): " + ", ".join(sorted(migrated)))
        return 1

    ENV.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    EXAMPLE.write_text("\n".join(cleaned_example) + "\n", encoding="utf-8")
    print(f"Migrated {len(migrated)} secret value(s) into .env (gitignored) and reset .env.example "
          "placeholders. Variable names only (values never printed): " + ", ".join(sorted(migrated)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
